import Foundation

/// A scenario described as data (JSON), used for downloadable scenario packs and scenarios generated by Claude.
///
/// Text fields may contain `{placeholders}` that are filled from the randomised `FlightContext`
/// (see `Template.placeholders`). Pilot steps are checked by the same analyser as the built-in scenarios, and
/// `validate()` proves every example call passes its own checks before a scenario is accepted.
public struct ScenarioDefinition: Codable, Hashable, Sendable {
    public var id: String
    public var title: String
    public var summary: String
    /// `controlled`, `uncontrolled`, `enRoute` or `emergency`.
    public var category: String
    public var briefing: [BriefingEntry]
    public var steps: [StepDefinition]

    public struct BriefingEntry: Codable, Hashable, Sendable {
        public var label: String
        public var value: String
    }

    public struct StepDefinition: Codable, Hashable, Sendable {
        /// `call` (pilot call or report, callsign first), `readback` (reply to ATC, callsign last),
        /// `emergency` (MAYDAY / PAN, callsign anywhere) or `atc` (ATC transmits, no reply).
        public var kind: String
        public var station: String
        /// ATC transmission played before the pilot's turn ("" for none).
        public var atc: String
        /// Instruction shown to the student ("" for `atc` steps).
        public var task: String
        /// Example of a correct pilot transmission ("" for `atc` steps).
        public var model: String
        public var elements: [ElementDefinition]
        /// Optional named cautions: `takeoffWord`, `lineUpOnly`, `noClearances`.
        public var cautions: [String]

        public init(kind: String, station: String, atc: String = "", task: String = "", model: String = "",
                    elements: [ElementDefinition] = [], cautions: [String] = []) {
            self.kind = kind
            self.station = station
            self.atc = atc
            self.task = task
            self.model = model
            self.elements = elements
            self.cautions = cautions
        }

        public init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            kind = try c.decode(String.self, forKey: .kind)
            station = try c.decodeIfPresent(String.self, forKey: .station) ?? ""
            atc = try c.decodeIfPresent(String.self, forKey: .atc) ?? ""
            task = try c.decodeIfPresent(String.self, forKey: .task) ?? ""
            model = try c.decodeIfPresent(String.self, forKey: .model) ?? ""
            elements = try c.decodeIfPresent([ElementDefinition].self, forKey: .elements) ?? []
            cautions = try c.decodeIfPresent([String].self, forKey: .cautions) ?? []
        }
    }

    public struct ElementDefinition: Codable, Hashable, Sendable {
        /// `phrase` (regex `patterns`), `number`, `pressure`, `altitude`, `squawk`, `runway` (numeric `value`),
        /// `aircraftType`, or `station` (`value` = station name).
        public var type: String
        public var label: String
        public var value: String
        public var patterns: [String]
        public var required: Bool

        public init(type: String, label: String, value: String = "", patterns: [String] = [], required: Bool = true) {
            self.type = type
            self.label = label
            self.value = value
            self.patterns = patterns
            self.required = required
        }

        public init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            type = try c.decode(String.self, forKey: .type)
            label = try c.decodeIfPresent(String.self, forKey: .label) ?? ""
            value = try c.decodeIfPresent(String.self, forKey: .value) ?? ""
            patterns = try c.decodeIfPresent([String].self, forKey: .patterns) ?? []
            required = try c.decodeIfPresent(Bool.self, forKey: .required) ?? true
        }
    }

    public static let stepKinds: Set<String> = ["call", "readback", "emergency", "atc"]
    public static let elementTypes: Set<String> = ["phrase", "number", "pressure", "altitude", "squawk", "runway",
                                                   "aircraftType", "station"]
    public static let cautionNames: [String: Caution] = [
        "takeoffWord": .takeoffWord, "lineUpOnly": .lineUpOnly, "noClearances": .noClearances,
    ]

    // MARK: - Decoding

    public static func decode(_ data: Data) throws -> ScenarioDefinition {
        try JSONDecoder().decode(ScenarioDefinition.self, from: data)
    }

    public func encoded() throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return try encoder.encode(self)
    }

    // MARK: - Building

    public func makeScenario() -> Scenario {
        let definition = self
        return Scenario(id: id, title: title, summary: summary,
                        category: ScenarioCategory(key: category) ?? .enRoute) { ctx in
            definition.script(for: ctx)
        }
    }

    public func script(for ctx: FlightContext) -> Script {
        let values = Template.values(for: ctx)
        func fill(_ s: String) -> String { Template.fill(s, values) }

        let steps = self.steps.map { def -> Step in
            let station = fill(def.station)
            let atc = def.atc.isEmpty ? nil : fill(def.atc)
            let elements = def.elements.map { Self.element(from: $0, ctx: ctx, fill: fill) }
            let cautions = def.cautions.compactMap { Self.cautionNames[$0] }
            switch def.kind {
            case "atc":
                return Step.atcOnly(station, atc ?? "")
            case "readback":
                return Step.readback(station, atc: atc ?? "",
                                     task: def.task.isEmpty ? "Read back the instruction." : fill(def.task),
                                     elements: elements, model: fill(def.model), cautions: cautions)
            case "emergency":
                return Step(station: station, atc: atc, task: fill(def.task), elements: [.callsign()] + elements,
                            model: fill(def.model), callsignPosition: .any, cautions: cautions)
            default:
                return Step.call(station, atc: atc, task: fill(def.task), elements: elements,
                                 model: fill(def.model), cautions: cautions)
            }
        }
        let stations = Set(self.steps.map { fill($0.station) }).sorted()
        return Script(briefing: briefing.map { BriefingItem(fill($0.label), fill($0.value)) },
                      steps: steps, vocabulary: ScenarioLibrary.baseVocabulary + stations)
    }

    static func element(from def: ElementDefinition, ctx: FlightContext, fill: (String) -> String) -> Element {
        let label = fill(def.label)
        let value = fill(def.value)
        switch def.type {
        case "number", "pressure":
            return .number(label.isEmpty ? value : label, value, required: def.required)
        case "altitude":
            let feet = Int(value.filter(\.isNumber)) ?? 0
            let e = Element.altitude(feet, required: def.required)
            return label.isEmpty ? e : Element(label: label, patterns: e.patterns, required: def.required, numericValue: e.numericValue)
        case "squawk":
            return .squawk(value.isEmpty ? ctx.squawk : value, required: def.required)
        case "runway":
            return .runway(value.isEmpty ? ctx.runway : value, required: def.required)
        case "aircraftType":
            return .type(ctx.aircraft, required: def.required)
        case "station":
            let s = Element.station(value.isEmpty ? label : value)
            return Element(label: s.label, patterns: s.patterns, required: def.required, kind: .station)
        default:
            return Element(label: label, patterns: def.patterns.map(fill), required: def.required)
        }
    }

    // MARK: - Validation

    /// Returns a list of problems (empty when the scenario is usable). Checks structure, placeholders and regexes,
    /// then analyses every example call against its own checks across `runs` random flights.
    public func validate(runs: Int = 20) -> [String] {
        var problems: [String] = []
        if title.trimmingCharacters(in: .whitespaces).isEmpty { problems.append("Title is empty.") }
        if ScenarioCategory(key: category) == nil {
            problems.append("Unknown category \"\(category)\" (use controlled, uncontrolled, enRoute or emergency).")
        }
        if steps.isEmpty { problems.append("There are no steps.") }
        if !steps.contains(where: { $0.kind != "atc" }) { problems.append("There are no pilot steps.") }
        if steps.count > 30 { problems.append("Too many steps (\(steps.count)); keep it under 30.") }

        var texts: [(String, String)] = [("title", title), ("summary", summary)]
        for b in briefing { texts += [("briefing label", b.label), ("briefing value", b.value)] }

        let sample = FlightContext.random()
        let values = Template.values(for: sample)

        for (i, step) in steps.enumerated() {
            let n = "Step \(i + 1)"
            if !Self.stepKinds.contains(step.kind) {
                problems.append("\(n): unknown kind \"\(step.kind)\" (use call, readback, emergency or atc).")
            }
            if step.station.isEmpty { problems.append("\(n): station is empty.") }
            if step.kind == "atc" || step.kind == "readback", step.atc.isEmpty {
                problems.append("\(n): \(step.kind) steps need an ATC transmission.")
            }
            if step.kind != "atc" {
                if step.task.isEmpty && step.kind != "readback" { problems.append("\(n): task is empty.") }
                if step.model.isEmpty { problems.append("\(n): example call (model) is empty.") }
            }
            texts += [("\(n) atc", step.atc), ("\(n) task", step.task), ("\(n) model", step.model), ("\(n) station", step.station)]
            for c in step.cautions where Self.cautionNames[c] == nil {
                problems.append("\(n): unknown caution \"\(c)\".")
            }
            for e in step.elements {
                if !Self.elementTypes.contains(e.type) { problems.append("\(n): unknown element type \"\(e.type)\".") }
                texts += [("\(n) element label", e.label), ("\(n) element value", e.value)]
                if e.type == "phrase" {
                    if e.patterns.isEmpty { problems.append("\(n): phrase element \"\(e.label)\" has no patterns.") }
                    for p in e.patterns {
                        texts.append(("\(n) pattern", p))
                        if (try? NSRegularExpression(pattern: Template.fill(p, values))) == nil {
                            problems.append("\(n): pattern \"\(p)\" is not a valid regular expression.")
                        }
                    }
                }
                if ["number", "pressure", "altitude"].contains(e.type), Template.fill(e.value, values).isEmpty {
                    problems.append("\(n): \(e.type) element \"\(e.label)\" needs a value.")
                }
            }
        }
        for (field, text) in texts {
            for p in Template.unknownPlaceholders(in: text) {
                problems.append("Unknown placeholder {\(p)} in \(field).")
            }
        }
        guard problems.isEmpty else { return problems }

        // Every example call must score 100% with no findings, whatever the randomised details.
        var reported = Set<Int>()
        var g = SystemRandomNumberGenerator()
        for _ in 0..<runs {
            let ctx = FlightContext.random(using: &g)
            let script = self.script(for: ctx)
            for (i, step) in script.steps.enumerated() where step.task != nil && !reported.contains(i) {
                let a = Analyzer.analyze(transcript: step.model ?? "", step: step, context: ctx,
                                         abbreviationAllowed: script.abbreviationAllowed(at: i, context: ctx))
                let missing = a.elements.filter { !$0.matched }.map(\.element.label)
                if a.score < 100 || !a.findings.isEmpty || !missing.isEmpty {
                    reported.insert(i)
                    var msg = "Step \(i + 1): the example call \"\(step.model ?? "")\" fails its own checks"
                    if !missing.isEmpty { msg += "; not found: \(missing.joined(separator: ", "))" }
                    if !a.findings.isEmpty { msg += "; problems: \(a.findings.map(\.title).joined(separator: "; "))" }
                    msg += ". (Normalised as: \"\(a.canonical)\".)"
                    problems.append(msg)
                }
            }
        }
        return problems
    }
}

/// `scenario-packs/index.json`: the list of scenario files in a pack.
public struct ScenarioPackIndex: Codable, Sendable {
    public var version: Int
    public var scenarios: [String]
}

/// `{placeholder}` substitution for scenario text.
public enum Template {
    /// Placeholder name → description, for documentation and for generating scenarios.
    public static let placeholders: [(String, String)] = [
        ("cs", "full callsign, spoken (\"Golf Alpha Bravo Charlie Delta\")"),
        ("ab", "abbreviated callsign, spoken (\"Golf Charlie Delta\")"),
        ("reg", "registration as written (\"G-ABCD\")"),
        ("type", "aircraft type as spoken by the pilot (\"PA twenty eight\")"),
        ("typeCode", "aircraft type designator (\"PA28\")"),
        ("rw", "runway, spoken (\"two six\")"),
        ("runway", "runway digits (\"26\")"),
        ("qnh", "QNH, spoken (\"one zero one three\")"),
        ("qnhValue", "QNH digits (\"1013\")"),
        ("qfe", "QFE, spoken"),
        ("qfeValue", "QFE digits"),
        ("rps", "regional pressure setting, spoken"),
        ("rpsValue", "regional pressure setting digits"),
        ("region", "altimeter setting region name (\"Chatham\")"),
        ("atis", "ATIS letter, phonetic (\"Charlie\")"),
        ("atisLetter", "ATIS letter (\"C\")"),
        ("atisLower", "ATIS letter lower-case, for patterns (\"c\")"),
        ("wind", "surface wind, spoken (\"two four zero degrees, one two knots\")"),
        ("windText", "surface wind as written (\"240° / 12 kt\")"),
        ("squawk", "assigned squawk, spoken (\"four five two one\")"),
        ("squawkCode", "assigned squawk digits (\"4521\")"),
        ("pob", "persons on board, spoken (\"two\")"),
        ("pobValue", "persons on board digits (\"2\")"),
        ("circuit", "circuit direction, lower-case (\"left\" or \"right\")"),
        ("Circuit", "circuit direction, capitalised"),
    ]

    public static func values(for c: FlightContext) -> [String: String] {
        [
            "cs": c.callsign, "ab": c.abbreviatedCallsign, "reg": c.registration,
            "type": c.aircraft.spoken, "typeCode": c.aircraft.code,
            "rw": Phonetic.runway(c.runway), "runway": c.runway,
            "qnh": Phonetic.digits(c.qnh), "qnhValue": String(c.qnh),
            "qfe": Phonetic.digits(c.qfe), "qfeValue": String(c.qfe),
            "rps": Phonetic.digits(c.regionalPressure), "rpsValue": String(c.regionalPressure),
            "region": c.regionName,
            "atis": Phonetic.letters[c.atis] ?? String(c.atis), "atisLetter": String(c.atis),
            "atisLower": String(c.atis).lowercased(),
            "wind": Phonetic.wind(direction: c.windDirection, speed: c.windSpeed),
            "windText": String(format: "%03d° / %d kt", c.windDirection, c.windSpeed),
            "squawk": Phonetic.squawk(c.squawk), "squawkCode": c.squawk,
            "pob": Phonetic.digitWords[c.personsOnBoard], "pobValue": String(c.personsOnBoard),
            "circuit": c.circuit, "Circuit": c.circuit.capitalized,
        ]
    }

    static let placeholderPattern = "\\{([A-Za-z]+)\\}"

    public static func fill(_ text: String, _ values: [String: String]) -> String {
        guard text.contains("{") else { return text }
        return text.replacingRegex(placeholderPattern) { groups in values[groups[1]] ?? groups[0] }
    }

    public static func unknownPlaceholders(in text: String) -> [String] {
        guard text.contains("{"), let re = try? NSRegularExpression(pattern: placeholderPattern) else { return [] }
        let known = Set(placeholders.map(\.0))
        let ns = text as NSString
        return re.matches(in: text, range: NSRange(location: 0, length: ns.length))
            .map { ns.substring(with: $0.range(at: 1)) }
            .filter { !known.contains($0) }
    }
}
